variable "allocated_storage" {}
variable "engine" {}
variable "engine_version" {}
variable "instance_class" {}
variable "db_name" {}
variable "username" {}
variable "password" {}
variable "db_subnet_group_name" {}
variable "vpc_security_groups_ids" {}
variable "identifier" {}
variable "skip_final_snapshot" {}